export interface InventoryOutputListItem {
    inventoryOutputId: number;
    companyId: number;
    orderDate: string;
    slipNo: string;
    slipNote: string | null;
    batchStatus: string;
    sumPlanQuantity: number;
    sumActualQuantity: number;
    outputStatus: string;
    isClosed: string;
    checked: string;
    planOutputDate: string;
    planWorkingDate: string;
    planDeliverDate: string;
    planSupplierSlipNo: string | null;
    actualOutputDate: string | null;
    actualDeliverDate: string | null;
    actualSupplierSlipNo: string | null;
    planCustomerDeliveryDestinationId: number;
    planDestinationCode: string;
    planDestinationName: string | null;
    actualCustomerDeliveryDestinationId: number;
    actualDestinationCode: string;
    actualDestinationName: string | null;
    planCustomerId: number;
    planCustomerCode: string;
    planCustomerName: string;
    actualCustomerId: number;
    actualCustomerCode: string;
    actualCustomerName: string;
    planRepositoryId: number;
    planRepositoryCode: string;
    planRepositoryName: string;
    actualRepositoryId: number;
    actualRepositoryCode: string;
    actualRepositoryName: string;
    supplierCode: string;
    supplierName: string;
    ownerCode: string;
    ownerName: string;
    createSlipType: string;
    routeCode: string;
    courseCode: string;
    deliverDestinationName: string;
    phoneNumber: string | null;
    faxNumber: string | null;
    postCode: string | null;
    newDestinationName: string | null;
}

export interface InventoryOutputSearchParams {
    orderDateFrom?: string;
    orderDateTo?: string;
    planOutputDateFrom?: string;
    planOutputDateTo?: string;
    planOutputWorkingDateFrom?: string;
    planOutputWorkingDateTo?: string;
    planOutputDeliveryDateFrom?: string;
    planOutputDeliveryDateTo?: string;
    supplierSlipNoFrom?: string;
    supplierSlipNoTo?: string;
    slipNoFrom?: string;
    slipNoTo?: string;
    customerIdFrom?: string;
    customerIdTo?: string;
    customerName?: string;
    deliveryDestinationIdFrom?: string;
    deliveryDestinationIdTo?: string;
    deliveryDestinationName?: string;
    supplierIdFrom?: string;
    supplierIdTo?: string;
    supplierName?: string;
    ownerIdFrom?: string;
    ownerIdTo?: string;
    ownerName?: string;
    productIdFrom?: string;
    productIdTo?: string;
    productName?: string;
    planRepositoryIdFrom?: string;
    planRepositoryIdTo?: string;
    batchNumber?: number;
    deliveryType?: string;
    deliveryStatus?: string;
    isClosed?: string;
    actualOutputDateFrom?: string;
    actualOutputDateTo?: string;
    actualDeliveryDateFrom?: string;
    actualDeliveryDateTo?: string;
    page?: number;
    pageSize?: number;
    sort?: string;
}
export interface InventoryOutputPlanHeader {
    inventoryOutputId: number;
    companyId: number;
    orderDate: string;
    planOutputDate: string;
    planWorkingDate: string;
    planDeliverDate: string;
    actualOutputDate: string | null;
    actualDeliverDate: string | null;
    createSlipType: string;
    slipNo: string;
    planSupplierSlipNo: string | null;
    actualSupplierSlipNo: string | null;
    slipNote: string | null;
    planCustomerDeliveryDestinationId: number;
    actualCustomerDeliveryDestinationId: number;
    planCustomerId: number;
    actualCustomerId: number;
    planRepositoryId: number;
    actualRepositoryId: number;
    batchStatus: string;
    sumPlanQuantity: number;
    sumActualQuantity: number;
    outputStatus: string;
    isClosed: string;
    routeCode: string;
    courseCode: string;
    deliverDestinationName: string | null;
    phoneNumber: string | null;
    faxNumber: string | null;
    postCode: string | null;
    address1: string | null;
    address2: string | null;
    address3: string | null;
    address4: string | null;
    newDestinationName: string | null;
    checked: string;
    planDestinationCode: string;
    planDestinationName: string | null;
    actualDestinationCode: string;
    actualDestinationName: string | null;
    planCustomerCode: string;
    planCustomerName: string;
    actualCustomerCode: string;
    actualCustomerName: string;
    planRepositoryCode: string;
    planRepositoryName: string;
    actualRepositoryCode: string;
    actualRepositoryName: string;
}

export interface InventoryOutputPlanDetail {
    datetimeMng: string | null;
    planDetailId: number;
    inventoryOutputId: number;
    companyId: number;
    productId: number;
    repositoryId: number;
    locationId: number | null;
    numberMng: string | null;
    csPlanQuantity: number | null;
    blPlanQuantity: number | null;
    psPlanQuantity: number | null;
    totalPlanQuantity: number;
    inventoryProductType: string;
    detailNote: string | null;
    freeItem1: string | null;
    freeItem2: string | null;
    freeItem3: string | null;
    productCode: string;
    productName: string;
    detailRepositoryCode: string;
    detailRepositoryName: string;
    locationCode: string | null;
    packCsUnitName: string;
    packBlUnitName: string;
    pieceUnitName: string;
    datetimeMngType: string | null;
    isDatetimeMng: string;
    isNumberMng: string;
    isPackCsInput: string;
    isPackBlInput: string;
    isPieceInput: string;
    totalQuantityInput: number;
    standardInfo: string | null;
    datetimeMngFrom: string | null;
    datetimeMngTo: string | null;
    numberMngFrom: string | null;
    numberMngTo: string | null;
    productOwnerId: number;
    supplierId: number;
    planCsPrice: number;
    planBlPrice: number;
    planPiecePrice: number;
    tax: number;
    amountTotal: number;
    batchStatus: string;
    batchNo: string;
    billingPackType: string;
    isBatchInprogress: number;
    ownerCode: string;
    ownerName: string;
    supplierCode: string;
    supplierName: string;
    totalActualQuantity: number | null;
    packCsAmount?: number;
    packBlAmount?: number;
    delFlg: string;
    saleCsPrice?: number;
    saleBlPrice?: number;
    salePiecePrice?: number;
}


export interface InventoryOutputPlanResponse {
    inventoryOutputPlanHeader: InventoryOutputPlanHeader;
    inventoryOutputPlanDetails: InventoryOutputPlanDetail[];
}

export interface InventoryOutputActualHeader {
    inventoryOutputId: number;
    companyId: number;
    planOutputDate: string;
    outputActualDate: string;
    createSlipType: string;
    slipNo: string;
    actualSupplierSlipNo: string | null;
    actualSlipNote: string | null;
    actualSupplierDeliveryDestinationId: number;
    actualSupplierId: number;
    productOwnerId: number;
    actualRepositoryId: number;
    outputStatus: string;
    sumPlanQuantity: number;
    sumActualQuantity: number;
    isClosed: string;
    freeItem1: string | null;
    freeItem2: string | null;
    freeItem3: string | null;
    contactStatus: string;
    destinationCode: string;
    departmentName: string | null;
    supplierCode: string;
    supplierName: string;
    customerCode: string;
    customerName: string;
    repositoryCode: string;
    repositoryName: string;
}

export interface InventoryOutputActualDetail {
    datetimeMng: string | null;
    actualDetailId: number;
    inventoryOutputId: number;
    companyId: number;
    productId: number;
    repositoryId: number;
    locationId: number | null;
    numberMng: string | null;
    csActualQuantity: number | null;
    blActualQuantity: number | null;
    psActualQuantity: number | null;
    totalActualQuantity: number;
    inventoryProductType: string;
    detailNote: string | null;
    productCode: string;
    productName: string;
    detailRepositoryCode: string;
    detailRepositoryName: string;
    locationCode: string | null;
    packCsUnitName: string;
    packBlUnitName: string;
    pieceUnitName: string;
    datetimeMngType: string | null;
    isDatetimeMng: string;
    isNumberMng: string;
    isPackCsInput: string;
    isPackBlInput: string;
    isPieceInput: string;
    totalQuantityInput: number;
    standardInfo: string | null;
    packCsAmount?: number;
    packBlAmount?: number;
    outputActualDate: string | null;
    delFlg: string;
}

export interface InventoryOutputActualResponse {
    inventoryOutputActualHeader: InventoryOutputActualHeader;
    inventoryOutputActualDetails: InventoryOutputActualDetail[];
}

export interface InventoryOutputCorrectionHeader {
    inventoryOutputId: number;
    companyId: number;
    planOutputDate: string;
    outputActualDate: string;
    createSlipType: string;
    slipNo: string;
    actualSupplierSlipNo: string | null;
    actualSlipNote: string | null;
    actualSupplierDeliveryDestinationId: number;
    actualSupplierId: number;
    productOwnerId: number;
    actualRepositoryId: number;
    outputStatus: string;
    sumPlanQuantity: number;
    sumActualQuantity: number;
    isClosed: string;
    freeItem1: string | null;
    freeItem2: string | null;
    freeItem3: string | null;
    contactStatus: string;
    destinationCode: string;
    departmentName: string | null;
    supplierCode: string;
    supplierName: string;
    customerCode: string;
    customerName: string;
    repositoryCode: string;
    repositoryName: string;
}

export interface InventoryOutputCorrectionDetail {
    datetimeMng: string | null;
    actualDetailId: number;
    inventoryOutputId: number;
    companyId: number;
    productId: number;
    repositoryId: number;
    locationId: number | null;
    numberMng: string | null;
    csActualQuantity: number | null;
    blActualQuantity: number | null;
    psActualQuantity: number | null;
    totalActualQuantity: number;
    inventoryProductType: string;
    detailNote: string | null;
    productCode: string;
    productName: string;
    detailRepositoryCode: string;
    detailRepositoryName: string;
    locationCode: string | null;
    packCsUnitName: string;
    packBlUnitName: string;
    pieceUnitName: string;
    datetimeMngType: string | null;
    isDatetimeMng: string;
    isNumberMng: string;
    isPackCsInput: string;
    isPackBlInput: string;
    isPieceInput: string;
    totalQuantityInput: number;
    standardInfo: string | null;
    packCsAmount?: number;
    packBlAmount?: number;
    outputActualDate: string | null;
    correctionReason: string | null;
    delFlg: string;
}

export interface InventoryOutputCorrectionResponse {
    inventoryOutputCorrectionHeader: InventoryOutputCorrectionHeader;
    inventoryOutputCorrectionDetails: InventoryOutputCorrectionDetail[];
}
